### ISSUE TITLE
upx is a dependency

### ISSUE THREAD

**Issue by hous** [podiki/libtcod-mac#5]
Heads up, upx is a dependency for the samples.

Before making the samples, e.g.
`make -f makefiles/makefile-samples-linux-sdl2 release`
or
`make -f makefiles/makefile-samples-linux-sdl release`
you'll need to
`brew install upx`

p.s. Thanks for all the hard work getting this ported to OSX!

**Comment by podiki** [comment]
Right you are, thanks!

Note that the upstream libtcod development has moved and seems to be alive again. It sounds like they will fold in the OS X fixes back in, but I'm not sure of the current status.

See: https://www.reddit.com/r/roguelikes/comments/39yt3l/the_libtcod_bitbucket_repo_has_moved/
and: https://www.reddit.com/r/roguelikes/comments/3a38pv/libtcod_development_need_mac_os_x_developers/
