### ISSUE TITLE
Calling console_blit causes Segmentation Fault 11

### ISSUE THREAD

**Issue by jdob** [podiki/libtcod-mac#6]
I'm not quite sure what else to report. I tried this having built with both SDL and SDL2. I've tried blitting two non-root consoles and I still see the issue. Any advice?

Thanks :)

**Comment by podiki** [comment]
Hmm...do you have a minimal example that does this? On my end I just tried the code from the [python libtcod tutorial](http://www.roguebasin.com/index.php?title=Complete_Roguelike_Tutorial,_using_python%2Blibtcod). That uses console_blit for instance, and works just fine.

**Comment by jdob** [comment]
Ok, so in trying to reproduce this with something simple, I kinda got it to work.

I tried to create an example inside of my clone of this repository. I copied the Generalization sample from the tutorial to a file under python/ and updated the libtcod.py to point to ../ for the dylib file. I ran that example and it worked correctly, with the blits. \o/

It doesn't work in my codebase, but at this point I'm 99% positive I missed copying something over. If I check it into git, would you mind looking at what I have to see if you can see what's missing?

What I did was:
- copy libtcod.dylib to my [project_root]/lib directory
- copy libtcod.py to my [project_root]/[project_name]/lib directory
- updated libtcod to look for the dylib file under "./lib", under the idea that I'll run my code from my project_root.
- copied the Generalization sample from the wiki to somewhere in my source and run it

All of that works for the tutorial code until the blits, when I get the segfault. Since the tutorial example runs from within the libtcod-mac directory but not my codebase, I'm pretty confident I'm missing something that I should have copied over to my codebase as well. I'll continue to experiment, but if you can think of anything I'm missing from that list of stuff I copied over, I'd appreciate it.

Thanks  :D

**Comment by podiki** [comment]
There are some image files that are used (libtcod expects it's fonts as images in a certain format), that is my guess of what you are missing. There is terminal.png in the root folder of libtcod, and there's the data folder with a lot more. I would check that.

**Comment by jdob** [comment]
I think I got it. I only copied libtcod.py but not cprotos.py. Once I copied that and changed the import in libtcod.py, it works  \o/

Sorry for the user error, I'll close this out. Thanks again :D

**Comment by podiki** [comment]
Ah right, cprotos.py, completely forgot about that. Thanks for the update, and glad you figured it out. If this repo ends up being the "official" Mac port, then I should add instructions about things like this for people to follow, so thanks for the information.

**Comment by jdob** [comment]
I'll keep notes on what I find to help you out with those instructions. This is my first playing with libtcod at all, and I'm doing it on both Mac and Linux, so hopefully I'll help flush out some of the bits for new devs.

**Comment by jstitch** [comment]
Does it makes sense that, using Linux, making MAC flag True works? I was getting the same segmentation fault until I did that

**Comment by podiki** [comment]
Hmm, sorry I do not know. For Linux though you should be using the actual libtcod which is under active development and supports linux: [libtcod (bitbucket)](https://bitbucket.org/libtcod/libtcod)

**Comment by jstitch** [comment]
that's the one I'm using in fact... anyway, thanks

**Comment by podiki** [comment]
I would ask upstream then. I'm not sure what that flag would do with that version though, as they do not support Mac. Probably some leftover code, so I'm not sure what that is doing for you exactly.
