### ISSUE TITLE
Trying to compile & run on OSX 10.11

### ISSUE THREAD

**Issue by jfcaron3** [podiki/libtcod-mac#8]
I have here a summary of a partially-successful attempt to build & run libtcod on OSX 10.11 using libraries from MacPorts.

1) The dependencies (SDL2, upx, ...) are available from MacPorts as well as homebrew.  
2) The samples do not compile out of the box following the instructions.  To get them to compile I had to do the following:
2a) Add $(SDL_LIBS) to CFLAGS in makefile-samples-linux-sdl2
2b) Comment out all the conditional crap about SDL.h from samples_c.c and samples_cpp.cpp and just write #include <SDL.h>
3) The samples run, but various features end up crashing the demo.  I can provide more details if someone will actually investigate.
4) The python sample starts to run, but it crashes with an Abort trap: 6

Unfortunately I wish to use the python bindings, so the partial success is not enough to let me do the tutorial I found.

**Comment by podiki** [comment]
Sorry, I have not used MacPorts before and have not been keeping up with `libtcod`. I (and I think others) have gotten it to compile and the examples to work, including a full [tutorial in python ](http://www.roguebasin.com/index.php?title=Complete_Roguelike_Tutorial,_using_python%2Blibtcod).

So the first question is how does MacPorts set up a build environment and what are the difference between using the Homebrew setup. Have you tried following the instructions in the readme with `brew`? Even though I have not been active with this project recently, I'd be happy to get it working in MacPorts as well.

Edit:
I'm not sure I follow your comment about makefile-samples-linux-sdl2. `$(SDL_LIBS)` should not need to be added to `CFLAGS` to make SDL projects. Unless maybe there is something funky with this makefile on your system?

Also, I know the samples do not work on anything but the SDL2 renderer, as they are set up currently. But otherwise they work.

**Comment by jfcaron3** [comment]
I am not trying to install libtcod via MacPorts, I meant I got the dependencies from MacPorts.  I still compiled libtcod separately with clang.

It's very possible that the SDL_LIBS thing was not needed, but that plus a few other attempts at fixing the problem were needed to get rid of 
`samples/samples_c.c:20:10: fatal error: 'SDL/SDL.h' file not found`

Any idea why I would be getting an Abort trap: 6 from python?  It happens after the samples_py.py script prints the line:
`***** Custom listener *****`

**Comment by podiki** [comment]
Yes, I understood how you were using MacPorts. Your error about not finding the SDL headers must come down to how MacPorts sets some things up versus Homebrew. I remember getting a similar error and that was one of the changes made to the libtcod code to get it to compile in Mac.

Maybe I had not tried that python sample before, I also get a crash at that point now. Are you still having trouble with the C/C++ samples? Since I have that working, I want to check that is okay first. I would also check using the python code from the tutorial I linked (probably the one you were thinking of too?), since that should also work.

As for the error with `samples_py.py`, I'm not sure yet what is happening there yet...

**Comment by jfcaron3** [comment]
I can't even do "import libtcodpy".  I get this error:

`>>> import libtcodpy

> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "libtcodpy.py", line 131, in <module>
> > >     setup_protos(_lib)
> > >   File "cprotos.py", line 9, in setup_protos
> > >     lib.TCOD_line_step.restype = c_bool
> > > AttributeError: 'NoneType' object has no attribute 'TCOD_line_step'
> > > `

I haven't had time to look into this error, since I am still at work.  Actually now I get this error also from samples_py.py.  I need to do this more carefully...

**Comment by podiki** [comment]
I see. Well something has gone wrong with either dependencies, compiling, or having the built libtcod libraries available. Please check that everything builds correctly (you end up with libtcod.dylib, libtcodgui.dylib, libtcodxx.dylib). Again, I have not used MacPorts so can only say that with a working Homebrew setup this works. Perhaps if you find a reference for the differences in where they put libraries and set things up, that will help.

**Comment by jfcaron3** [comment]
Ok here is a more meticulous attempt, from a fresh directory:

```
$ git clone https://github.com/podiki/libtcod-mac.git
$ cd libtcod-mac/
$ make -f makefiles/makefile-osx-sdl2 release
```

At this point I have the .dylibs that you mention.  There were lots of warnings but no errors from the compilation.  I can import libtcodpy from python after messing with the path a bit, but I don't get too far into the tutorial since it can't find the font files and such. 

Now for the samples:

```
$ make -f makefiles/makefile-samples-linux-sdl2 
\mkdir -p /tmp/libtcod/debug/samples
gcc  -Iinclude -I. -Wall `sdl2-config --cflags` -g -o /tmp/libtcod/debug/samples/samples_c.o -c samples/samples_c.c 
samples/samples_c.c:20:10: fatal error: 'SDL/SDL.h' file not found
#include <SDL/SDL.h>
         ^
1 error generated.
make: *** [/tmp/libtcod/debug/samples/samples_c.o] Error 1
```

It is looking for the SDL header, not SDL2, so somehow the macro TCOD_SDL2 is not being defined properly.  I have both versions of SDL installed from MacPorts.  The headers are kept in /opt/local/include/SDL and /opt/local/include/SDL2.

**Comment by jfcaron3** [comment]
I just also tried the SDL 1 version:

```
$ make -f makefiles/makefile-osx release
gcc  -Iinclude -Iinclude/gui -Wall `sdl-config --cflags`  -fno-strict-aliasing -fPIC -ansi -DNDEBUG -O2 -s -o /tmp/libtcod/release/bresenham_c.o -c src/bresenham_c.c
clang: warning: argument unused during compilation: '-s'
gcc  -Iinclude -Iinclude/gui -Wall `sdl-config --cflags`  -fno-strict-aliasing -fPIC -ansi -DNDEBUG -O2 -s -o /tmp/libtcod/release/bsp_c.o -c src/bsp_c.c
clang: warning: argument unused during compilation: '-s'
gcc  -Iinclude -Iinclude/gui -Wall `sdl-config --cflags`  -fno-strict-aliasing -fPIC -ansi -DNDEBUG -O2 -s -o /tmp/libtcod/release/color_c.o -c src/color_c.c
clang: warning: argument unused during compilation: '-s'
In file included from src/color_c.c:29:
include/libtcod_int.h:38:10: fatal error: 'SDL/SDL.h' file not found
#include <SDL/SDL.h>
         ^
1 error generated.
make: *** [/tmp/libtcod/release/color_c.o] Error 1
```

It is not finding SDL/SDL.h because sdl-config --cflags is giving it /opt/local/include/SDL as a directory, not /opt/local/include.  If I add "-I/opt/local/include" to the CFLAGS variable in makefile/makefile-osx, then it compiles with lots of warnings but no errors.

Now if I try the SDL 1 samples:

```
$ make -f makefiles/makefile-samples-linux release
gcc  -Iinclude -I. -Wall -O2 -s -o /tmp/libtcod/release/samples/samples_c.o -c samples/samples_c.c 
clang: warning: argument unused during compilation: '-s'
In file included from samples/samples_c.c:13:
include/libtcod.h:109:10: fatal error: 'SDL.h' file not found
#include <SDL.h>
         ^
1 error generated.
make: *** [/tmp/libtcod/release/samples/samples_c.o] Error 1
```

I tried adding "-I/opt/local/include/" to makefiles/makefile-samples-linux, but it still couldn't find SDL.h because it's asking for it without the leading SDL/ directory.  If I add "-I/opt/local/include/SDL" now it works for libtcod.h, but a later file (samples_c.c) asks for <SDL/SDL.h>.  So in the end I added BOTH: -I/opt/local/include -I/opt/local/include/SDL to CFLAGS in makefiles/makefile-samples-linux.  This allowed the samples to compile without errors, and all 3 compiled samples work.

I can import libtcodpy in python after messing with the path, as in my attempt with SDL2, but again it can't find fonts and stuff.  I can probably figure out that part.

I will now try again with the SDL2 version to see what simple modifications I can make to the makefiles to get everything to compile.

**Comment by jfcaron3** [comment]
I am still not able to run the python example with the SDL 1 build (Abort trap 6).  

I tried running an example program from Part 1 of the tutorial: it doesn't crash, but no window pops up, I just get an infinite spinning OSX beachball after this prints:

```
24 bits font.
key color : 0 0 0
24bits greyscale font. converting to 32bits
```

I have to Ctrl+C to exit the infinite beachball.

**Comment by podiki** [comment]
I would stick just with SDL2, as that is what I made sure was working here. Also, it looks like upstream has moved to only SDL2 (not SDL1) as well. Best to prepare for that and not worry about very old SDL1.

So the main issues you are having is with finding SDL headers and libraries. You might want to look at the [FAQ on the SDL website](http://wiki.libsdl.org/FAQLinux) for some help getting that sorted. Using Homebrew had similar changes that had to be made, but looks like you at least got it to compile, though hopefully it could be done more automatically with `sdl2-config`.

The fonts and that sort of thing is in `data` in this repository. You need to have both `libtcod.py` and `cprotos.py` somewhere python can find it (e.g. in the same directory as your python code). Additionally, you need the `.dylib` files produced when you built libtcod (again, easiest to just have them in the same directory as your python code).

**Comment by jfcaron3** [comment]
Sorry for not updating.  I was able to get the tutorial examples working by just copying the *.py, *.dylib and resource files into the base directory (I didn't realize this is standard procedure).  

This is with the SDL2 build.  I didn't bother trying to fix the samples.

Thanks for the help.

**Comment by podiki** [comment]
You are welcome. If you have all the steps for compiling with Macports sorted out, feel free to add them to the readme in a pull request. Unfortunately I haven't still haven't had time to reconcile this fork with upstream, but that could still be useful to others in the meantime.
